Week_7/W7D1/rails_olympics_practice/build_rails_project/GardenParty/config/routes.rb
Rails.application.routes.draw do

  resources :users
  resources :gardens
  resources :flowers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Week_7/W7D1/rails_olympics_practice/build_rails_project/GardenParty/app/models/flower.rb
class Flower < ApplicationRecord
    validates :flower_type, presence: true

    belongs_to :gardener,
        foreign_key: :gardener_id,
        class_name: :User

    belongs_to :garden,
        foreign_key: :garden_id,
        class_name: :Garden


end

Week_7/W7D1/rails_olympics_practice/build_rails_project/GardenParty/app/models/garden.rb
class Garden < ApplicationRecord
    validates :name, :size, presence: true
    validates :name, uniqueness: {scope: :garden_owner_id}

    belongs_to :garden_owner,
        foreign_key: :garden_owner_id,
        class_name: :User

    has_many :flowers,
        foreign_key: :garden_id,
        class_name: :Flower

end

Week_7/W7D1/rails_olympics_practice/build_rails_project/GardenParty/app/models/user.rb
class User < ApplicationRecord
    validates :username, presence: true, uniqueness: true

    has_many :gardens,
        foreign_key: :garden_owner_id,
        class_name: :Garden

    has_many :flowers,
        foreign_key: :gardener_id,
        class_name: :Flower

    has_many :flowers_in_all_gardens,
        through: :gardens,
        source: :flowers

    has_many :gardens_with_my_flowers,
        through: :flowers,
        source: :garden
    
end

Week_7/W7D1/rails_olympics_practice/build_rails_project/GardenParty/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

Week_7/W7D1/rails_olympics_practice/build_rails_project/GardenParty/app/controllers/flowers_controller.rb
class FlowersController < ApplicationController
  
    def create
        flower = Flower.create(flower_param)

        flower.save
        redirect_to garden_url(flower_param[:garden_id])
    end

    def destroy
        flower = Flower.find(params[:id])
        flower.destroy
        redirect_to garden_url(flower.garden_id)
    end


    private

    def flower_param
        self.params.require(:flower).permit(:flower_type, :gardener_id, :garden_id)
    end
end

Week_7/W7D1/rails_olympics_practice/build_rails_project/GardenParty/app/controllers/gardens_controller.rb
class GardensController < ApplicationController
  
    def index
        @gardens = Garden.all
        render :index
    end

    def show
        @garden = Garden.find(params[:id])
        render :show
    end

    def create
        garden = Garden.create(garden_param)

        if garden.save
            redirect_to gardens_url
        else
            render :new
        end
    end

    private

    def garden_param
        self.params.require(:garden).permit(:name, :size, :garden_owner_id)
    end
end

Week_7/W7D1/rails_olympics_practice/build_rails_project/GardenParty/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new # not necessary, pulled from AppCon already
    render :new
  end

  def create
    user = User.create(user_param)
    if user.save
        redirect_to gardens_url
    else
        render :new
    end
  end

  private

  def user_param
    self.params.require(:user).permit(:username)
  end

end

Week_7/W7D1/rails_olympics_practice/build_rails_project/GardenParty/app/helpers/flowers_helper.rb
module FlowersHelper
end

Week_7/W7D1/rails_olympics_practice/build_rails_project/GardenParty/app/helpers/gardens_helper.rb
module GardensHelper
end

Week_7/W7D1/rails_olympics_practice/build_rails_project/GardenParty/app/helpers/users_controller_helper.rb
module UsersControllerHelper
end

Week_7/W7D1/rails_olympics_practice/build_rails_project/GardenParty/app/helpers/users_helper.rb
module UsersHelper
end

Week_7/W7D1/rails_olympics_practice/build_rails_project/GardenParty/app/views/gardens/index.html.erb
<h1>All the Gardens!</h1>
<ul>
  <% @gardens.each do |garden| %>
    <%= garden.name %>
  <% end %>
</ul>

Week_7/W7D1/rails_olympics_practice/build_rails_project/GardenParty/app/views/gardens/new.html.erb
<h1>Create a new Garden!</h1>

<form action="<%= gardens_url %>" method="POST">
    <input
      type="hidden"
      name="authenticity_token"
      value="<%= form_authenticity_token %>">
    <label>Choose a garden name:
        <input name ="garden[name]" value="">
    </label>
    <label>Choose a garden size:
        <input name ="garden[size]" value="">
    </label>
        <input type="hidden" name ="garden[user_id]" value=<%= User.last.id %>>
    <button type="submit">Create A New Garden</button>
</form>

Week_7/W7D1/rails_olympics_practice/build_rails_project/GardenParty/app/views/gardens/show.html.erb
<h1>This is a garden!</h1>

<h2><%= @garden.name %></h2>
<h4>Size: <%= @garden.size %></h4>

<h5>Flowers:</h5>
<ul><%@garden.flowers.each do |flower| %>
    <%= flower.flower_type %>
    <% end%>
</ul>

<form action="<%= flowers_url %>" method="POST">
    <input
      type="hidden"
      name="authenticity_token"
      value="<%= form_authenticity_token %>">
    <label>Choose a Flower type to add:
        <input name ="flower[flower_type]" value="">
    </label>
        <input type="hidden" name ="flower[user_id]" value=<%= User.last.id %>>
        <input type="hidden" name ="flower[garden_id]" value=<%= @garden.id %>>
    <button type="submit">Create A Flower</button>
</form>

Week_7/W7D1/rails_olympics_practice/build_rails_project/GardenParty/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GardenParty</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

Week_7/W7D1/rails_olympics_practice/build_rails_project/GardenParty/app/views/users/new.html.erb
<h1>Create a new User!</h1>

<form action="<%= users_url %>" method="POST">
    <input
      type="hidden"
      name="authenticity_token"
      value="<%= form_authenticity_token %>">
      
    <label>Choose a user name:
        <input name ="user[username]" value="">
    </label>
    <button type="submit">Create New User</button>
</form>

Week_7/W7D1/rails_olympics_practice/build_rails_project/GardenParty/app/views/users/show.html.erb
<h1>Hello <%= @user.username %>!</h1>